export const companies = [
  {
    id: 1,
    name: 'EPAM',
    photoUrl: 'https://fakeimg.pl/60x60?font=lobster',
    description: 'A leading global provider of digital services.',
    yearEstablished: 1993,
    numberOfEmployees: 50000,
    headquarters: 'Newtown, Pennsylvania, USA',
    website: 'https://www.epam.com',
  },
  {
    id: 2,
    name: 'Uber',
    photoUrl: 'https://fakeimg.pl/60x60?font=lobster',
    description: 'Ride-sharing company that connects drivers and riders.',
    yearEstablished: 2009,
    numberOfEmployees: 26000,
    headquarters: 'San Francisco, California, USA',
    website: 'https://www.uber.com',
  },
  {
    id: 3,
    name: 'SoftServe',
    photoUrl: 'https://fakeimg.pl/60x60?font=lobster',
    description: 'IT and consulting services company.',
    yearEstablished: 1993,
    numberOfEmployees: 10000,
    headquarters: 'Lviv, Ukraine',
    website: 'https://www.softserveinc.com',
  },
  {
    id: 4,
    name: 'Laboratory',
    photoUrl: 'https://fakeimg.pl/60x60?font=lobster',
    description: 'Innovative laboratory services provider.',
    yearEstablished: 2010,
    numberOfEmployees: 200,
    headquarters: 'San Diego, California, USA',
    website: 'https://www.laboratory.com',
  },
  {
    id: 5,
    name: 'GlobalLogic',
    photoUrl: 'https://fakeimg.pl/60x60?font=lobster',
    description: 'Digital product engineering and software development.',
    yearEstablished: 2000,
    numberOfEmployees: 18000,
    headquarters: 'San Francisco, California, USA',
    website: 'https://www.globallogic.com',
  },
  {
    id: 6,
    name: 'Luxoft',
    photoUrl: 'https://fakeimg.pl/60x60?font=lobster',
    description: 'A global IT service provider.',
    yearEstablished: 2000,
    numberOfEmployees: 13000,
    headquarters: 'Zurich, Switzerland',
    website: 'https://www.luxoft.com',
  },
  {
    id: 7,
    name: 'Ciklum',
    photoUrl: 'https://fakeimg.pl/60x60?font=lobster',
    description: 'Software engineering and technology partner.',
    yearEstablished: 2002,
    numberOfEmployees: 3000,
    headquarters: 'London, United Kingdom',
    website: 'https://www.ciklum.com',
  },
  {
    id: 8,
    name: 'DataArt',
    photoUrl: 'https://fakeimg.pl/60x60?font=lobster',
    description: 'Global technology consultancy.',
    yearEstablished: 1997,
    numberOfEmployees: 4000,
    headquarters: 'New York City, New York, USA',
    website: 'https://www.dataart.com',
  },
  {
    id: 9,
    name: 'Infopulse',
    photoUrl: 'https://fakeimg.pl/60x60?font=lobster',
    description: 'IT service provider and consulting firm.',
    yearEstablished: 1991,
    numberOfEmployees: 1000,
    headquarters: 'Kyiv, Ukraine',
    website: 'https://www.infopulse.com',
  },
  {
    id: 10,
    name: 'Miratech',
    photoUrl: 'https://fakeimg.pl/60x60?font=lobster',
    description: 'IT and business services provider.',
    yearEstablished: 1989,
    numberOfEmployees: 1500,
    headquarters: 'New York City, New York, USA',
    website: 'https://www.miratechgroup.com',
  },
  {
    id: 11,
    name: 'Intellias',
    photoUrl: 'https://fakeimg.pl/60x60?font=lobster',
    description: 'IT service provider for global enterprises.',
    yearEstablished: 2002,
    numberOfEmployees: 1000,
    headquarters: 'Lviv, Ukraine',
    website: 'https://www.intellias.com',
  },
  {
    id: 12,
    name: 'XYZ Company',
    photoUrl: 'https://fakeimg.pl/60x60?font=lobster',
    description: 'Innovative solutions for modern businesses.',
    yearEstablished: 2015,
    numberOfEmployees: 500,
    headquarters: 'Los Angeles, California, USA',
    website: 'https://www.xyzcompany.com',
  },
];

export const companies2 = [
  {
    id: 1,
    name: 'EPAM',
    photoUrl: 'https://fakeimg.pl/60x60?font=lobster',
    description: 'A leading global provider of digital services.',
  },
  {
    id: 2,
    name: 'Uber',
    photoUrl: 'https://fakeimg.pl/60x60?font=lobster',
    description: 'Ride-sharing company that connects drivers and riders.',
  },
  {
    id: 3,
    name: 'SoftServe',
    photoUrl: 'https://fakeimg.pl/60x60?font=lobster',
    description: 'IT and consulting services company.',
  },
  {
    id: 4,
    name: 'Laboratory',
    photoUrl: 'https://fakeimg.pl/60x60?font=lobster',
    description: 'Innovative laboratory services provider.',
  },
  {
    id: 5,
    name: 'GlobalLogic',
    photoUrl: 'https://fakeimg.pl/60x60?font=lobster',
    description: 'Digital product engineering and software development.',
  },
  {
    id: 6,
    name: 'Luxoft',
    photoUrl: 'https://fakeimg.pl/60x60?font=lobster',
    description: 'A global IT service provider.',
  },
  {
    id: 7,
    name: 'Ciklum',
    photoUrl: 'https://fakeimg.pl/60x60?font=lobster',
    description: 'Software engineering and technology partner.',
  },
  {
    id: 8,
    name: 'DataArt',
    photoUrl: 'https://fakeimg.pl/60x60?font=lobster',
    description: 'Global technology consultancy.',
  },
  {
    id: 9,
    name: 'Infopulse',
    photoUrl: 'https://fakeimg.pl/60x60?font=lobster',
    description: 'IT service provider and consulting firm.',
  },
  {
    id: 10,
    name: 'Miratech',
    photoUrl: 'https://fakeimg.pl/60x60?font=lobster',
    description: 'IT and business services provider.',
  },
  {
    id: 11,
    name: 'Intellias',
    photoUrl: 'https://fakeimg.pl/60x60?font=lobster',
    description: 'IT service provider for global enterprises.',
  },
  {
    id: 12,
    name: 'XYZ Company',
    photoUrl: 'https://fakeimg.pl/60x60?font=lobster',
    description: 'Innovative solutions for modern businesses.',
  },
];