name: Deploy action
on:
  push:
    branches:
      - "**"
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm install

      - name: Build application
        env:
          PORT: ${{ secrets.PORT }}
          VITE_BASE_URL: ${{ secrets.VITE_BASE_URL}}
          VITE_TIMEOUT: ${{ secrets.VITE_TIMEOUT }}
          VITE_WS_URL: ${{ secrets.VITE_WS_URL }}
        run: npm run build

      - name: Deploy static site to S3 bucket
        run: aws s3 sync ./dist s3://meduzzen-quizzes --delete